### PR TITLE
Issue #73 Kong Enterprise Edition Support

### LINKED ISSUE #73: Kong Enterprise Support
I'd like to expand terraform-provider-kong to support Kong EE entities (RBAC, workspace, etc.) and I believe the first step is to build in support in this client. 

I have some preliminary work done in a branch that provides workspace support, I'm looking to finish out RBAC in the near future. 

I'm opening this issue for any feedback and to track the upcoming PR.

### PR DESCRIPTION
**Pull request by tjrivera**
Hello, 

This PR looks to provide support for enterprise edition entities within gokong. My team at Comcast has been using your [Terraform kong provider](https://github.com/kevholditch/terraform-provider-kong),  recently acquired an Enterprise license for Kong, and wanted to configure some of those enterprise features using the provider. In order to do that we knew we had to provide support in this client library first. This PR seeks to do that. 

This PR adds
* The option to make the gokong client "workspace aware" -- In the enterprise edition users, services, routes, plugins, permissions, etc. can be created on the standard paths that Kong CE uses, or they can be created in the context of a workspace. 
* The ability to manage: 
  * Workspaces
  * Workspace entities
  * Users
  * Admins
  * Roles
  * Endpoint permissions
  * Entity permissions

This PR also adds the ability to test the enterprise features provided you have a license. By setting the `KONG_LICENSE` environment variable to a json encoded string containing your license and `KONG_REPOSITORY` and `KONG_VERSION` to set the docker image and tag respectively EE tests will be run, otherwise they are skipped. 

Apologies for the size of this PR. We just received approval to make this open-source contribution so it's been queued up for some time. We have a related PR for the terraform-provider-kong repository that piggy-backs off of this work to support these entities in Terraform configurations using that provider. 

Thanks for your work on this project, let me know if there's anything I can clarify!

Closes #73

### CODE REVIEW

**Comment by marcelometal** [comment]
Hi @tjrivera,

me (@marcelometal), @MayconDionisio and @luccamendonca are working to improve goKong and some MRs were merged in the last months. The latest upstream activity was on Nov 14, 2019, but there are 9 MRs opened since Nov 19 until Jan 16. We are adding Kong EE features, like workspaces. All these MRs are public and were applied on our fork at https://github.com/globocom/gokong (branch globocom).

There is other golang lib, [go-kong](https://github.com/hbagdi/go-kong) and on Dec 23, 2019 @hbagdi [proposed](https://github.com/Kong/kubernetes-ingress-controller/issues/487) to @kevholditch to merge both their projects, but got no answer.

After a few months without upstream activity, we [Globocom](https://github.com/globocom/) are thinking about maintain our own project and no longer a fork. @tjrivera and @hbagdi what do you think? Would you like to join us on this new project?

Opened MRs:

* Kong EE's workspaces support & support for running tests with custom Dockerfile https://github.com/kevholditch/gokong/pull/70
* Added Tags field https://github.com/kevholditch/gokong/pull/69
* Bump defaultKongVersion to 1.4 https://github.com/kevholditch/gokong/pull/68
* Return error when kong returns Bad request https://github.com/kevholditch/gokong/pull/67
* Travis: Bump golang and kong version https://github.com/kevholditch/gokong/pull/66
* Return an error when DeleteServiceById gets a 400 https://github.com/kevholditch/gokong/pull/64
* Creating interfaces for Clients https://github.com/kevholditch/gokong/pull/63
* Consumer: Fixed duplicated key 'custom_id' https://github.com/kevholditch/gokong/pull/61
* Id tests and added MarshalYAML and UnmarshalYAML https://github.com/kevholditch/gokong/pull/60

**Comment by tjrivera** [comment]
Hi @marcelometal!

The team on our side is happy to move to an actively maintained fork and to collaborate moving forward. Our main use case for this library is for downstream use in [terraform-provider-kong](https://github.com/kevholditch/terraform-provider-kong). Our team also makes use of the decK utility written by @hbagdi so we have some experience with [go-kong](https://github.com/hbagdi/go-kong) as well. 

We've done a great deal of work to build out EE support on this fork but my gut tells me that consolidating both clients using [go-kong](https://github.com/hbagdi/go-kong) as the base might be the best path forward. We started with this client (kevholditch/gokong) solely based on its relationship to the terraform provider. In practice, we've noticed some serious performance issues when managing a large number of resources. The downside there would be a significant rework of the existing Terraform provider to tie it to hbagdi/go-kong, but that's not a showstopper. 

That being said, I'm open to coordinating with your team to merge in some of our updates around RBAC and the like. We merged in your tags branch just this morning!

**Comment by hbagdi** [comment]
Hello everyone,

Thanks for the ping here. First of all, I'm really happy to see this PR. It is always encouraging to see our Open-Source community and enterprise customers come together and work on solutions to extend and enhance our products.

There has been a great interest in the community and enterprise users for bindings to Admin API of Kong in various languages. Go is probably the most popular language in the infrastructure software space and we have seen quite a few Admin API bindings in the wild and some home-grown solutions by customers as well. Some of the popular ones have already been called out above.

The way I see it, having several implementation and even more forks fosters innovation, but it does lead to fragmentation in the ecosystem. I'd prefer if all of us can get together and converge to a single solution rather than starting or maintaining yet another solution.
I do get the reasons for people forking to add in a customization but overall I would really like to keep that to minimum.

Our Open-Source community always creates such solutions and we see contributors come and go as they adopt Kong into their infrastructure. But, once Open-Sourced, these solution impose a burden on the authors. The authors move on to different companies and projects and the repository becomes stale with open issues and PRs. I think Kong, Inc. could help here and I'm going to see how we can help to reduce the time spent on maintenance. We can all better use our time if we don't have to work on the same problem several times.

Re `hbagdi/go-kong`, the package has been extensively used in Kong's Ingress Controller and decK, which have been in production use for over a year at this point. The library is also maintained and kept up to date with all the recent Kong releases, complete with integrations tests for each version of Kong and is currently compatible with Kong 2.0. 

As concrete next steps, I'd like to propose:
- I'd love to help out in migrating the Terraform provider to `hbagdi/go-kong`. If the migration requires any addition to `go-kong`, we can make those changes as well.
- With proliferation of these libraries and considering how much folks are dependent on these, I'll try to see if we can get a library accepted as a Kong Official library. This helps with long-term maintenance, get engineering time from Kong, Inc on it, while preserving the Open-Source spirit.

I'd love to hear everyone's thoughts on this.

Harry

**Comment by tjrivera** [comment]
Hi @hbagdi!

Thanks for joining the discussion! Our team is in full support of converging community efforts around one go implementation to support Kong Admin API bindings and for that effort to reside in  `hbagdi/go-kong` repo. We already incorporate decK into our workflow but still have use cases where Terraform or low-level client bindings are more appropriate. 

We would be interested in incorporating support for the following objects in this library:

* Workspaces
* Workspace entities
* Users
* Admins
* Roles
* Endpoint permissions
* Entity permissions

And to have that support translate to a community-supported Terraform provider. 

We're excited to see these features get built out so that we can optimize our use of Kong in our infrastructure, and even more pumped to see community and industry support behind those efforts.

At this point, does it make sense to start building out proposals outside of this project? We're also interested in what @marcelometal and his team have in mind. 

Thanks!

**Comment by luccamendonca** [comment]
Hey @hbagdi and @tjrivera! Thanks a lot for the answers!

@marcelometal and I are really happy with the repercussion of this PR as well as with how fast you guys replied to our first comment :)

We're currently using and contributing with `kevholditch/gokong` to create an internal CLI that should be used to configure our multiple Kong workspaces in a "self-service" manner, so each one of our internal customers would be able to manipulate entities within their own workspace. In fact, the actual goal is to have the CLI transformed into a k8s operator controller, so it should be completely transparent for the end-user. P.s.: if building a k8s controller is in your plans, please let us know, so we don't duplicate even more code!

Now... we've been working on it for the last couple months, but as of yesterday (and thanks to this thread!) we've discovered `decK` and started messing with it. As of now, it seems to fulfill almost each one of our needs regarding Kong configuration and manipulation, therefore we might just migrate to it and start extending it to some specific needs we have, such as manipulating single entities (mainly services and consumers) without needing to actually dump a whole workspace or even database.

Apart from that specific need, `decK` seems like a very powerful and complete tool.

We were thinking, then, that it could be a good idea do move this conversation - and probably our PRs features - to @hbagdi 's `go-kong` repo, focusing our efforts on it instead of trying to maintain what seems to be a dead project. It would be specially good if Kong, Inc ends up supporting its development somehow :)

Last but not least, we'd really like to thank @kevholditch for the nice work made with `gokong`, which helped us with our development and allowed us to actually deliver some great things. But, unfortunately, given the lack of responsiveness, we should probably move on :)


Please, let us know what you guys think.

Thanks!

**Comment by kevholditch** [comment]
Hey all, sorry for the lack of responsiveness been crazy busy with new baby and work. If any of you would like to volunteer to be an admin on the project to help review PRs would be happy to add you. I don’t have a lot of time to give to this at the moment

**Comment by luccamendonca** [comment]
Hey @kevholditch!

Don't worry at all about that. We hope your baby's fine and that everything stays cool at work :)
Also, the community always finds its way!

Well, I talked to @marcelometal here and if you wanted to make at least one of us an admin of your repository we thought about only changing the README to let people know that we may take a while to respond here and, if things go that way, give directions to `hbagdi/go-kong` as the suggested maintained project.

Once again, there's no need to feel sorry at all and thanks a lot for answering :)

**Comment by hbagdi** [comment]
Sounds good to me.
Following are the actions items that I can see:
- Port over this PR to `hbagdi/go-kong`
- Port over the terraform module to use `hbagdi/go-kong`
- Kevin needs to help out with the above migrations or share the maintenance responsibility with one of the other members. 

That should standardize one REST binding library.

Thank you for your quick responses on this!
Looking forward to us making progress on this front.

**Comment by kevholditch** [comment]
@hbagdi have invited you to this repo so you can help with this.  I think it would also be good to get the kong provider added to the official terraform registry that way you don't have to faff about with a customer provider when using it.

**Comment by tjrivera** [comment]
Sounds good to me. I'll create an issue in `hbagdi/go-kong` for the ported PR to land against. There's some work that I'll have to do there to match the conventions in go-kong, but I don't suspect it will take a ton of cycles, just need to fit it into my existing work.

**Comment by hbagdi** [comment]
> @hbagdi have invited you to this repo so you can help with this. I think it would also be good to get the kong provider added to the official terraform registry that way you don't have to faff about with a customer provider when using it.

Thank you, Kevin!
Is it possible to invite one of us to the Terraform provider repo as well?
We will have to make changes to add support for the other lib in there.

**Comment by kevholditch** [comment]
@hbagdi no worries Harry, have added you to the terraform provider too.  One thing to bear in mind is that at the moment we have two branches in the Terraform provider one for kong 0.x and one for kong 1.x.  Form3 the company I work for are currently using the provider for kong 0.x as we haven't had a chance to upgrade kong yet.  So I'm keen to keep that branch on the provider in case we need to do any bug fixing etc.

**Comment by hbagdi** [comment]
This has now been incorporated into https://github.com/kong/go-kong

**Pull request closed without merging**
