### PR TITLE
Fix routes and services offset with kong 1.0.x

### LINKED ISSUE #39: Offset is UUID in routes/services for Kong 1.0
Offset is of type uuid as of Kong 1.0.  

As well, none of the query params are getting serialized properly because a pointer struct is being passed instead of the struct to the gorequest Query() func.  I have coded up fixes, but I suspect there's going to be a specific way you'd like to solve this.

### PR DESCRIPTION
**Pull request by secat**
Fixes #39

### CODE REVIEW

**Comment by secat** [comment]
@kevholditch this PR is ready for review. Thank you.

**Comment by kevholditch** [comment]
I have fixed the merge conflicts and merged in, thanks for the contribution

**Comment by secat** [comment]
Thank you!

**Comment by secat** [comment]
@kevholditch the fix seems not to be in the master branch...

I have fix the merge conflicts.

**Comment by kevholditch** [comment]
@secat sorry I think sorted the other one, can you open this PR again and I'll merge it

**Comment by secat** [comment]
@kevholditch I have open a new PR #59 with the fix and resolved merge conflicts

**Pull request closed without merging**
